### ISSUE TITLE
Please use a folder dialog where one can paste the full path

### ISSUE THREAD

**Issue by Tony20221** [sla80/SmartSvgViewer#4]
I hate folder dialogs where I have to click.. click.. click.. click.. click.. click... click... click. to some obscure subfolder.
I already have the path in the clipboard. Let me jump to that path quickly.

**Comment by sla80** [comment]
Hello @Tony20221!

Currently, you can do it this way: "File" / "Open File". In the Open File dialog box, paste (Ctrl+V) a folder string either into the Folder input field (at the top) or into the File input field (at the bottom), and press Enter. Your folder will open in a dialog box. Select any SVG file in it and click "Open". In the application, the file will be shown in preview, and the contents of the folder will be loaded as a thumbnail gallery.

But I understand perfectly what you mean. Because I remember those old days when the "Registry Editor" in Windows did not have a field for entering registry paths, it was a pain.

Okay, I'll think about how to make the folder entry dialog box more convenient.

P.S. By the way, the updated app will be released this weekend (you will get an update notification in the app).

**Comment by sla80** [comment]
Hello @Tony20221!

In update 0.5.0.1645, the folder open dialog was replaced with a modern one, similar to the file open dialog. In which there is a field for pasting the path from the clipboard. You will receive this version by auto-update.
